version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      .env
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  server:
    build: .
    container_name: MyPass
    hostname: MyPass
    ports:
      - "3000:3000"
    restart: always
    working_dir: /var/www/MyPass
    volumes:
      - .:/var/www/MyPass:Z
    env_file:
      .env
    tty: true
    stdin_open: true
    command: >
      bash -c "rm -f tmp/pids/server.pid
      && bundle exec rails s -b 0.0.0.0"
    depends_on:
      - db
